set(LUASTG_CMAKE_IMPORT_ROOT ${CMAKE_CURRENT_LIST_DIR})

include(${CMAKE_CURRENT_LIST_DIR}/cpm.cmake)

include(${CMAKE_CURRENT_LIST_DIR}/spdlog.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/json.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/simdutf.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/sdl3.cmake)

if (LUASTG_BUILD_RUNTIME)
    include(${CMAKE_CURRENT_LIST_DIR}/tracy.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/pugixml.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/stb.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/miniaudio.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/tinygltf.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/tinyobjloader.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/pcg.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/xxhash.cmake)
    include(${CMAKE_CURRENT_LIST_DIR}/ada_url.cmake)

    if (WIN32)
        include(${CMAKE_CURRENT_LIST_DIR}/wil.cmake)
        include(${CMAKE_CURRENT_LIST_DIR}/directx_tex.cmake)
        include(${CMAKE_CURRENT_LIST_DIR}/d3dcompiler.cmake)
    endif ()
endif ()
