add_executable(ShaderCompiler)
luastg_target_common_options(ShaderCompiler)
luastg_target_more_warning(ShaderCompiler)
target_compile_definitions(ShaderCompiler
PRIVATE
    _UNICODE
    UNICODE
    HREADER_OUTPUT_DIRECTORY=\"${CMAKE_CURRENT_LIST_DIR}/generated\"
    HREADER_INPUT_DIRECTORY=\"${CMAKE_CURRENT_LIST_DIR}\"
)
target_include_directories(ShaderCompiler
PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}
)
target_sources(ShaderCompiler
PRIVATE
    ShaderCompiler.cpp
)
target_link_libraries(ShaderCompiler
PRIVATE
    d3dcompiler.lib
)
