if (NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "LuaSTG Retro requires a 64-bit target")
endif ()

if (NOT DEFINED LUASTG_ARCH)
    if (APPLE AND CMAKE_OSX_ARCHITECTURES MATCHES "x86_64" AND CMAKE_OSX_ARCHITECTURES MATCHES "arm64")
        set(detected_arch "universal")
    elseif (CMAKE_GENERATOR_PLATFORM MATCHES "^[Xx]64$")
        set(detected_arch "amd64")
    elseif (CMAKE_GENERATOR_PLATFORM MATCHES "^[Aa][Rr][Mm]64$")
        set(detected_arch "arm64")
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
        set(detected_arch "amd64")
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|ARM64|aarch64|AARCH64)$")
        set(detected_arch "arm64")
    else ()
        message(FATAL_ERROR "LuaSTG Retro does not support architecture '${CMAKE_SYSTEM_PROCESSOR}'")
    endif ()

    set(LUASTG_ARCH "${detected_arch}" CACHE STRING "LuaSTG Retro target architecture" FORCE)
    unset(detected_arch)
endif ()

message(STATUS "LuaSTG Retro target architecture: ${LUASTG_ARCH}")
